// <auto-generated />
using System;
using Figure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Figure.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Figure.DataAccess.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("faaefd49-bf97-41c3-9931-93049b53665a"),
                            CreatedAt = new DateTime(2022, 10, 4, 14, 39, 51, 350, DateTimeKind.Local).AddTicks(4822),
                            Description = "description1",
                            Email = "adsfdfg",
                            IsArchived = false,
                            Name = "test1",
                            PhoneNumber = "9345435"
                        },
                        new
                        {
                            Id = new Guid("eb312f32-85fe-4f57-9ee3-1e6049fc0864"),
                            CreatedAt = new DateTime(2022, 10, 4, 14, 39, 51, 350, DateTimeKind.Local).AddTicks(4865),
                            Description = "description1",
                            Email = "adsfdfg",
                            IsArchived = false,
                            Name = "test1",
                            PhoneNumber = "9345435"
                        },
                        new
                        {
                            Id = new Guid("21265c05-4300-4853-8789-6406c9e65469"),
                            CreatedAt = new DateTime(2022, 10, 4, 14, 39, 51, 350, DateTimeKind.Local).AddTicks(4868),
                            Description = "description1",
                            Email = "adsfdfg",
                            IsArchived = false,
                            Name = "test1",
                            PhoneNumber = "9345435"
                        },
                        new
                        {
                            Id = new Guid("3594e1c9-2674-4396-8fa0-4d32435a94d1"),
                            CreatedAt = new DateTime(2022, 10, 4, 14, 39, 51, 350, DateTimeKind.Local).AddTicks(4872),
                            Description = "description1",
                            Email = "adsfdfg",
                            IsArchived = false,
                            Name = "test1",
                            PhoneNumber = "9345435"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
